export const siteConfig = {
  name: "VIZION",
  fullName: "VIZION STORE",
  tagline: "Streetwear Premium",
  slogan: "Vista sua visão.",
  url: "https://vizionstore.com.br",
  whatsapp: "5561981494548",
  whatsappDisplay: "(61) 98149-4548",
  instagram: "@vizionstore61",
  instagramUrl: "https://instagram.com/vizionstore61",
  cnpj: "62.823.573/0001-72",
  email: "viziononstore@gmail.com",
  address: "Ceilândia-DF - Qnp 19, Conjunto C, Casa 2",
  cep: "72319-192",
  mapsUrl: "https://www.google.com/maps/place/Qnp+19,+Conjunto+C+-+Ceilândia+Norte,+Ceilândia+-+DF",
};
